### ISSUE TITLE
high level enchantments not working

### ISSUE THREAD

**Issue by Belkhaa** [MarcusElg/Enchanting-Reimagined#1]
when i try to use a tool or weapon with fortune or looting that´s above level 3 it just doesn't apply at all

**Comment by MarcusElg** [comment]
> when i try to use a tool or weapon with fortune or looting that´s above level 3 it just doesn't apply at all

Are you combining a tool with an enchanted book or what are you trying to do?

**Comment by Belkhaa** [comment]
yes, i combine the enchantment with a tool and it doesn't apply when i use it, for example i put fortune 4-6 on a pickaxe and it acts like it doesn't have any fortune, i tried with each level from 4 to 6 and it doesn't seem to work, cool mod tho i really like the concept

**Comment by Belkhaa** [comment]
i used the special workbench and an anvil, with the enchanting workstation it applies to the tool but doesn't work when using the tool, with the anvil it just applies the maximum vanilla enchant

**Comment by MarcusElg** [comment]
I will look into it!

**Comment by MarcusElg** [comment]
Applying a fortune 4 book to a pickaxe gives it fortune 4 which does increase the drops when mining ores.
![image](https://github.com/user-attachments/assets/05df2cca-1056-4fcf-959a-32a901a35b66)

Could you create a small clip of what isn't working?

**Comment by Belkhaa** [comment]
after more testing i found that it was a fault in my modpack, with a veinminer datapack the effects only apply to one ore, the one i break but for every enchantment even vanilla, so it wasn't your mod. I´m so sorry for not checking properly and thank you for checking it.

just with your mod (mining 4, 8 and 12 ores):
![Captura de pantalla (12)](https://github.com/user-attachments/assets/f07c1c0a-1cf7-4c70-b572-90d7daef0120)

modpack (first two with the datapack, third without it), (mining 4, 12 and 12 ores):
![Captura de pantalla (13)](https://github.com/user-attachments/assets/48c73a2e-3a99-4d8d-8010-3d5476c5fd27)
