### ISSUE TITLE
Enchantment Extracting deletes modded items

### ISSUE THREAD

**Issue by AvaAsUsual** [MarcusElg/Enchanting-Reimagined#2]
Whenever trying to extract an enchantment from a piece of modded armor the modded armor will simply disappear into thin air
![image](https://github.com/user-attachments/assets/66589ab7-24d3-49b1-9f08-56722df06de6)
![image](https://github.com/user-attachments/assets/99ee6215-78c7-4b9f-b38e-ada8e41bf6ba)

**Comment by MarcusElg** [comment]
Extracting enchantments from tools/armour consumes the tools/armor. Either you keep the enchantments (in an enchanting workstation) or you keep the item (in a grindstone). I could add a config option for not consuming the item.

**Comment by MarcusElg** [comment]
![image](https://github.com/user-attachments/assets/ce3a5f6f-7a50-4bff-b372-7646362d1079)
Implemented config option in 1.1.0. Thanks for your suggestion!
