### ISSUE TITLE
Items that have had their enchantments extracted can no longer be enchanted

### ISSUE THREAD

**Issue by AvaAsUsual** [MarcusElg/Enchanting-Reimagined#3]
(Thank you for adding the config by the way!  I really appreciate it <3)
![image](https://github.com/user-attachments/assets/c43f007d-8f2c-430e-abcf-a3bb4fc0ea2c)
![image](https://github.com/user-attachments/assets/fc0010bf-a180-4640-92a4-c3e327c558be)

**Comment by MarcusElg** [comment]
Fixed, thanks :)
