### ISSUE TITLE
House in Savanna without workstation

### ISSUE THREAD

**Issue by KarmasuL** [MarcusElg/Enchanting-Reimagined#4]
The houses in savanna villages with the enchanting bottle have no enchanting workstation in them. 
There is a chest floating one block above the ground. So I assume the workstation is supposed to underneath that but the space is empty.
I've seen this happen in all savanna villages I've seen so far. I tried in a few different generated worlds. 
In other villages the enchanting workstation is there.
(Version 1.1.2 for MC 1.21.3)

**Comment by MarcusElg** [comment]
Will look into it. Sounds like the structure didn't save correctly

**Comment by MarcusElg** [comment]
Fixed in 1.1.3. Thanks for reporting!
