### ISSUE TITLE
Book Error

### ISSUE THREAD

**Issue by Halibear** [MarcusElg/Enchanting-Reimagined#5]
I got two enchanted books both with errors. The first says Might I then under says I AM ERROR. The second says Blowthrough I then under says LOOT TABLE ERROR - REPORT TO MOD/DATAPACK AUTHOR and under that says Illegal enchantment. I am using Fabric version 1.1.1 for Java 1.21.1

Please let me know if you need any more details.

Thanks.

**Comment by MarcusElg** [comment]
Include a picture of the error and instructions on how to reproduce it
